# .github/workflows/ci-build.yml

name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET 9.0 SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.100-preview.7'  # Update this to latest preview if available

      - name: Restore dependencies
        run: dotnet restore backend/backend.sln

      - name: Build project
        run: dotnet build backend/backend.sln --no-restore --configuration Release

      - name: Run tests
        run: dotnet test backend/backend.sln --no-build --verbosity normal
